version: '3.7'

services: 
    mongo:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
            - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
        ports: 
            - "${MONGO_PORT}:27017"
        networks:
            - comments_app

    docs:
        image: comments_docs
        build: 
            context: ./collections
        ports: 
            - "${DOCS_PORT}:5000"
        networks:
            - comments_app
networks:
    comments_app:
        driver: bridge
        name: comments_app 
            