version: '3.7'

services: 
    mongo:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
            - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
        ports: 
            - "${MONGO_PORT}:27017"
        networks:
            - comments_app

    comments:
        image: comments-app
        environment: 
            - MONGO_USERNAME=${MONGO_USERNAME}
            - MONGO_PASSWORD=${MONGO_PASSWORD}
            - MONGO_DB_NAME=${MONGO_DB_NAME}
            - MONGO_HOST=mongo
            - CHECK_TASK_URL=${CHECK_TASK_URL}
        build: 
            context: .
        ports: 
            - "${PORT}:8835"
        links:
            - mongo
        networks:
            #- kanban
            - comments_app

    docs:
        image: comments_docs
        build: 
            context: ./collections
        ports: 
            - "${DOCS_PORT}:5000"
        networks:
            - comments_app
networks:
    comments_app:
        driver: bridge
        name: comments_app 
        # if your are not using kanban gateway to deploy the application
        # just comment all the kanban network references in this docker-compose file ..
        #kanban:
            #driver: overlay
            #name: kanban 
                #external: 
                #name: kanban
            